accounts/urls.py
from django.conf.urls import patterns, url, include

from accounts.views import *

urlpatterns = patterns('',
    # Companies
    url(r'^members/$', Members.as_view(), name='members'),
    url(r'^members/(?P<pk>\d+)/promote/$', promote, name='promote'),
    url(r'^members/(?P<pk>\d+)/demote/$', demote, name='demote'),
    url(r'^add_user/$', AddUser.as_view(), name='add_user'),
    url(r'^update_profile/$', ProfileUpdate.as_view(), name='update_profile'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    'authtools.views.password_reset_confirm_and_login',
    name='password_reset_confirm'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
)

golf/urls.py
from django.conf.urls import patterns, include, url

from golf.views import Index

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('authtools.urls')),
    url(r'^textbits/', include('extra.urls', namespace='textbits')),
    url(r'^$', Index.as_view(), name='index'),
    url(r'^', include('tracker.urls', namespace='tracker')),
)

tracker/urls.py
from django.conf.urls import patterns, include, url
from tracker.views import * 

urlpatterns = patterns('',
    url(r'^$', Index.as_view(), name='index'),
    url(r'^times/$', Times.as_view(), name='times'),
    url(r'^(?P<pk>\d+)/$', Detail.as_view(), name='detail'),
    url(r'^create/$', Create.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/update/$', Update.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/delete/$', Delete.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/claim/$', claim, name="claim"),
    url(r'^(?P<pk>\d+)/unclaim/$', unclaim, name="unclaim"),
    url(r'^(?P<date>[0-9]{4}-[0-9]{1,2}-[0-9]{1,2})/$', Date.as_view(), name='day'),
    url(r'^(?P<date>[0-9]{4}-[0-9]{1,2})/$', Month.as_view(), name='month'),
)

extra/models.py
from django.db import models
from django.core.urlresolvers import reverse

class TextBit(models.Model):
    name = models.CharField(max_length=100, primary_key=True)
    content = models.TextField()

    def get_update_url(self):
        return reverse('textbits:update', args=[self.pk])

    def __unicode__(self):
        return self.name

class Title(models.Model):
    field = models.CharField(max_length=100, primary_key=True)
    name = models.CharField(max_length=100)

    @classmethod
    def load(cls):
        try:
            return cls.objects.get()
        except cls.DoesNotExist:
            return cls()

    def __unicode__(self):
        return self.name

tracker/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from datetime import datetime, timedelta

class TeeTime(models.Model):
    time = models.DateTimeField()
    person = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)
    date_edited = models.DateField(auto_now=True)

    def get_absolute_url(self):
        return reverse('tracker:detail', args=[self.pk])

    def get_update_url(self):
        return reverse('tracker:update', args=[self.pk])

    def get_delete_url(self):
        return reverse('tracker:delete', args=[self.pk])

    def get_claim_url(self):
        return reverse('tracker:claim', args=[self.pk])

    def get_unclaim_url(self):
        return reverse('tracker:unclaim', args=[self.pk])

    def get_date_url(self):
        return reverse('tracker:day', args=[(teetime.time).strftime('%Y-%m-%d')])

    def droppable(self):
        return self.time > datetime.today() + timedelta(days=7)

    def __unicode__(self):
        return self.time.strftime('%Y-%m-%d')

golf/views.py
from django.views.generic import TemplateView
from guardian.mixins import LoginRequiredMixin
from datetime import date

from tracker.models import TeeTime
from extra.models import TextBit, Title

class Index(LoginRequiredMixin, TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        context['textbit'] = TextBit.objects.get(name='Updates')
        context['object_list'] = TeeTime.objects.all() 
        today = date.today()
        context['month'] = "{0} {1}".format(today.year, today.month)
        if today.month == 12:
            context['month_next'] = "{0} {1}".format(today.year + 1, 1)
        else:
            context['month_next'] = "{0} {1}".format(today.year, today.month + 1)
        return context

golf/templates/base.html
<!DOCTYPE html>
{% load bootstrap3 %}
{% load staticfiles %}

<html>
  <head>
    <title>TeeTimer</title>
    <link rel="stylesheet" href="{% static 'css/flatly.css' %}" />
    {% bootstrap_javascript True %}
    {% block tinymce %}{% endblock tinymce %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".bs-navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">{{ Title }}</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'tracker:index' %}">Tee Times</a></li>
            <li><a href="{% url 'accounts:members' %}">Members</a></li>
            <li><a href="{% url 'tracker:times' %}">Time List</a></li>
            <li><a href="http://www.raccooncreek.com/">Course</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if perms.tracker.change_teetime %}
              {% block edit_link %}{% endblock %}
            {% endif %}
            {% if perms.tracker.add_teetime %}
              <li><a href="{% url 'tracker:create' %}"><span class="glyphicon glyphicon-plus"></span></a></li>
            {% endif %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.name }} <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="/accounts/update_profile">Update Profile</a></li>
                <li><a href="/accounts/password_reset">Reset Password</a></li>
                {% if perms.accounts.add_user %}
                  <li><a href="/accounts/add_user">Add User</a></li>
                {% endif %}
                {% if perms.is_staff %}
                  <li><a href="/admin">Admin Backend</a></li>
                {% endif %}
                <li><a href="/accounts/logout">Logout</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </header>
    <div class="col-md-10 col-md-offset-1">
      {% block content %}{% endblock content %}
    </div>
  </body>
</html>

golf/templates/index.html
{% extends "base.html" %}

{% block content %}
  {% include "tracker/calendars.html" with datetimes=object_list %}
  <h2>Updates{% if perms.extra.change_textbit %} - <a href="{{ textbit.get_update_url }}">Edit</a>{% endif %}</h2>
  {{ textbit.content|safe }}
{% endblock %}